### ISSUE TITLE
Building SciPy on cflinuxfs2 fails without a Fortran compiler

### ISSUE THREAD

**Issue by jpbufe3** [cloudfoundry/cflinuxfs2#23]
SciPy has a number of Fortran dependencies that require a compiler (such as `gfortran`) in order for compilation.

Example error when building:
`2015-11-11T18:13:00.15-0500 [STG/0] OUT Could not locate executable pathf95
2015-11-11T18:13:00.15-0500 [STG/0] OUT don't know how to compile Fortran code on platform 'posix'
2015-11-11T18:13:00.15-0500 [STG/0] OUT building 'dfftpack' library
2015-11-11T18:13:00.15-0500 [STG/0] OUT error: library dfftpack has Fortran sources but no Fortran compiler found
2015-11-11T18:13:00.15-0500 [STG/0] OUT ----------------------------------------
2015-11-11T18:13:00.16-0500 [STG/0] OUT Staging failed: Buildpack compilation step failed
2015-11-11T18:13:00.27-0500 [API/2] ERR encountered error: App staging failed in the buildpack compile phase`

**Comment by mavenraven** [comment]
Hey there @jpbufe3, have you tried https://github.com/thenovices/heroku-buildpack-scipy to see if it fits your use case?

**Comment by flavorjones** [comment]
@jpbufe3 This buildpack would also address your Atlas dependency from #23 and #24. Please let us know how you get on?

**Comment by jpbufe3** [comment]
Hi @mavenraven and @flavorjones,

I had previously been using that buildpack, but unfortunately it does not work on the `cflinuxfs2` stack (which prompted this issue and #24). It had previously worked on `lucid64`.

Below is an example error from using that buildpack:

```
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash md5 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type md5
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash sha1 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type sha1
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash sha224 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type sha224
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash sha256 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type sha256
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash sha384 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type sha384
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ERROR:root:code for hash sha512 was not found.
2015-11-12T12:05:34.14-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     globals()[__func_name] = __get_hash(__func_name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
2015-11-12T12:05:34.14-0500 [STG/0]      ERR     raise ValueError('unsupported hash type ' + name)
2015-11-12T12:05:34.14-0500 [STG/0]      ERR ValueError: unsupported hash type sha512
2015-11-12T12:05:34.30-0500 [STG/0]      ERR Traceback (most recent call last):
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "/app/.heroku/python/bin/pip", line 9, in <module>
2015-11-12T12:05:34.30-0500 [STG/0]      ERR     load_entry_point('pip==6.0.6', 'console_scripts', 'pip')()
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 519, in load_entry_point
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2310, in load
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2316, in resolve
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/__init__.py", line 15, in <module>
2015-11-12T12:05:34.30-0500 [STG/0]      ERR     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/vcs/mercurial.py", line 11, in <module>
2015-11-12T12:05:34.30-0500 [STG/0]      ERR     from pip.download import path_to_url
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/download.py", line 30, in <module>
2015-11-12T12:05:34.30-0500 [STG/0]      ERR     from pip._vendor import requests, six
2015-11-12T12:05:34.30-0500 [STG/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/__init__.py", line 81, in load_module
2015-11-12T12:05:34.30-0500 [STG/0]      ERR     raise ImportError("No module named '%s'" % (name,))
2015-11-12T12:05:34.30-0500 [STG/0]      ERR ImportError: No module named 'pip._vendor.requests'
2015-11-12T12:05:34.32-0500 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-11-12T12:05:34.46-0500 [API/0]      ERR encountered error: App staging failed in the buildpack compile phase
```

I'm not sure if this should ultimately fall to forcing users to modify/ create custom buildpacks or just including them as a part of the stack, but both `gfortran` and `libatlas-base-dev` are required on Ubuntu 14.04 for SciPy and NumPy (http://stackoverflow.com/a/31840553/4867335), which seemed like a popular enough use case to warrant adding them. This would then allow users to stay on the standard `https://github.com/cloudfoundry/python-buildpack`.

Let me know what you think.

**Comment by flavorjones** [comment]
I've asked the Buildpacks team to see if they can help get this to work, to avoid incurring the additional size increase to the rootfs for this package and atlas.

This will likely be early next week, so thanks in advance for your patience and for helping us understand!

**Comment by jtarchie** [comment]
@jpbufe3, we are constrained by multiple variables what can be added to the stack. Disk size of runnable containers limits how much we can add to root packages. And legacy support, as older versions of the stack won't have these packages,  we cannot guarantee that apps run consistently against multiple versions of cf-release core. 

As for the error messages above, since it is Heroku buildpack, it has a different `STACK` names. In your deployment [`manifest.yml`](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html), please add the following:

``` yaml
---
  buildpack: https://github.com/thenovices/heroku-buildpack-scipy
  env:
    STACK: cedar-14
```

Since this is a Heroku flavored buildpack, there are some minor differences. I was able to push out an app with Python and NumPy.

```
Starting app numpy-example in org pivotal / space integration as admin...
-----> Downloaded app package (2.8M)
-----> Downloaded app buildpack cache (59M)
Cloning into '/tmp/buildpacks/heroku-buildpack-scipy'...
-----> Noticed cffi. Bootstrapping libffi.
-----> Detected numpy/scipy in requirements.txt.
-----> Using cached binaries.
-----> Existing numpy (1.8.2) package detected.
-----> Installing dependencies with pip
-----> Uploading droplet (62M)

1 of 1 instances running
```

Let me know if that works for you.

**Comment by jpbufe3** [comment]
@jtarchie thank you for your response and fix. This seems to have fixed the issues I have been seeing and unblocks me. Thank you!

Is it the expectation going forward then that anyone trying to use these libraries will need to rely on this buildpack? It seems like something that would be valuable as either something the stack can handle or as a part of the default buildpack: https://github.com/cloudfoundry/python-buildpack

**Comment by jtarchie** [comment]
@jpbufe3 thanks for letting us know! Glad we could resolve that for you.

**Comment by flavorjones** [comment]
@jpbufe3 Right now we don't have plans to add these libraries and the `gfortran` compiler to the rootfs, simply because I'm not seeing demand for them from the community (other than from you! :) :)). 

Additionally, with the above workaround allowing you to do this at staging time, there's doesn't seem to be an urgent reason to make a decision now.

Please keep us in the loop if you have problems with the heroku buildpack. We've been noodling with ways to allow applications to more-easily install `.deb` packages, but haven't yet had a compelling use case to drive out actual user requirements.

Thanks for using Cloud Foundry!
